### ISSUE TITLE
NPM Confusion

### ISSUE THREAD

**Issue by DamnedScholar** [skypager/skypager#7]
[The NPM page](https://www.npmjs.com/package/skypager) for this repo has the version at `40.1.14`. Meanwhile, the `package.json` says it's `1.0.0` and the latest release is `1.2.4`.

**Comment by soederpop** [comment]
hey, so i've been using this package for several years and before switching to a scoped package and monorepo format, there were earlier versions that just used the `skypager-` prefix.  

the `skypager` package will install all of the @scoped dependencies
